<?php
/**
 * ricardo.ch AG - Switzerland
 *
 * @author      Sylvain Rayé <support at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2015 ricardo.ch AG (http://www.ricardo.ch)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var $this Mage_Core_Block_Template */

$user = Mage::getSingleton('admin/session')->getUser();
$isEnabled = Mage::getStoreConfigFlag(Diglin_Ricento_Helper_Data::CFG_STATS);
$testMode = Mage::getStoreConfigFlag(Diglin_Ricento_Helper_Data::CFG_STATS_TEST_MODE);
$appid = ($testMode) ? Mage::getStoreConfig(Diglin_Ricento_Helper_Data::CFG_STATS_APPID_TEST) : Mage::getStoreConfig(Diglin_Ricento_Helper_Data::CFG_STATS_APPID);

if ($isEnabled && $user && $user->getUsername()):
?>
<script>
    window.intercomSettings = {
        name: "<?php echo $user->getFirstname() . ' ' . $user->getLastname(); ?>",
        email: "<?php echo $user->getEmail(); ?>",
        created_at: <?php echo strtotime($user->getCreated()); ?>,
        "version": "<?php echo Mage::getConfig()->getModuleConfig('Diglin_Ricento')->version ?>",
        "shop": "<?php echo Mage::getStoreConfig('web/unsecure/base_url'); ?>",
        app_id: "<?php echo $appid ?>"
    };
</script>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/<?php echo $appid ?>';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>
<?php endif; ?>