<?php
/**
 * ricardo.ch AG - Switzerland
 *
 * @author      Sylvain Rayé <support at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2014 ricardo.ch AG (http://www.ricardo.ch)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $this Mage_Core_Block_Template */

?>
<div class="entry-edit">
    <img class="banner" src="<?php echo $this->getSkinUrl('ricento/images/banner.png'); ?>" title="ricardo.ch Banner" as="ricardo.ch Banner" height="90px" width="728px" />
</div>