<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author      Sylvain Rayé <sylvain.raye at diglin.com>
 * @category    Ricento
 * @package     Ricento
 * @copyright   Copyright (c) 2011-2014 Diglin (http://www.diglin.com)
 */
?>
<div id="category-tree">
    <?php echo $this->getChildHtml('toplevel'); ?>
    <div id="ricardo_children">
        <?php echo $this->getChildHtml('sublevel'); ?>
    </div>
</div>