<?php
/**
 * ricardo.ch AG - Switzerland
 *
 * @author      Sylvain Rayé <support at diglin.com>
 * @category    Diglin
 * @package     Diglin_Ricento
 * @copyright   Copyright (c) 2015 ricardo.ch AG (http://www.ricardo.ch)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @var $this Mage_Payment_Block_Info
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>:

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<div class="ricardo-payment-info">
<?php if (isset($_specificInfo['article_ids'])): ?>
<p><?php echo Mage::helper('diglin_ricento')->__('Articles: <strong>%s</strong>', $_specificInfo['article_ids']) ?></p>
<?php endif; ?>
<ul>
    <li><?php echo implode(' / ', $_specificInfo['methods']) ?></li>
    <?php if (isset($_specificInfo['information'])): ?><li><?php echo $_specificInfo['information']; ?></li><?php endif; ?>
</ul>
</div>
<?php endif;?>

<?php echo $this->getChildHtml()?>
